services:
  # React App
  client-app:
    container_name: ui
    extends:
      file: docker-compose.base.yml
      service: base
    command: npx nx serve hotline --host=0.0.0.0
    ports:
      - 80:4200
    networks:
      - psi-ops-network

  # Express App
  api:
    container_name: api
    extends:
      file: docker-compose.base.yml
      service: base
    env_file:
      - .env
    command: npx nx serve api --host=0.0.0.0
    ports:
      - 3333:3333
    networks:
      - psi-ops-network

  # Redis
  redis:
    container_name: redis
    image: redis:7.0.8
    volumes:
      - ./cache:/data
    env_file:
      - .env
    command: redis-server --loglevel notice
    ports:
      - 6379:6379
    networks:
      - psi-ops-network
  # database:
  #   container_name: postgres
  #   restart: always
  #   image: postgres:15.1
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   env_file:
  #     - .env
  #   ports:
  #     - 5432:5432
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready --dbname=reachdb --username=reachuser']
  #     interval: 1s
  #     timeout: 1s
  #     retries: 30
  #   networks:
  #     - psi-ops-network

networks:
  psi-ops-network:
    name: psi-ops-network
