version: '3.9'

services:
  base:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./apps/:/app/apps
      - ./node_modules/:/app/node_modules